"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const menu_1 = require("./src/view/menu");
const Inventory_1 = require("./src/model/Inventory");
const OrderController_1 = require("./src/controller/OrderController");
const MainController_1 = require("./src/controller/MainController");
const SupplierController_1 = require("./src/controller/SupplierController");
const InventoryController_1 = require("./src/controller/InventoryController");
const CustomerOrder_1 = require("./src/model/order/CustomerOrder");
const SupplierOrder_1 = require("./src/model/order/SupplierOrder");
const menu = new menu_1.Menu();
const inventory = new Inventory_1.Inventory();
const customerOrderController = new OrderController_1.OrderController(inventory, menu, CustomerOrder_1.CustomerOrder);
const supplierOrderController = new OrderController_1.OrderController(inventory, menu, SupplierOrder_1.SupplierOrder);
const supplierController = new SupplierController_1.SupplierController(menu);
const inventoryController = new InventoryController_1.InventoryController(menu);
supplierController.addNewAction("Place Purchase Order", supplierOrderController.rootAction.bind(supplierOrderController));
const menuControllers = new Map();
menuControllers.set('Place Order', customerOrderController);
menuControllers.set('Manage Suppliers', supplierController);
menuControllers.set('Manage Inventory', inventoryController);
const mainController = new MainController_1.MainController(menu, menuControllers);
mainController.rootAction();
