"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const menu_1 = require("./src/view/menu");
const Inventory_1 = require("./src/model/Inventory");
const OrderController_1 = require("./src/controller/OrderController");
const MainController_1 = require("./src/controller/MainController");
const SupplierController_1 = require("./src/controller/SupplierController");
const InventoryController_1 = require("./src/controller/InventoryController");
const menu = new menu_1.Menu();
const inventory = new Inventory_1.Inventory();
const orderController = new OrderController_1.OrderController(inventory, menu);
const supplierController = new SupplierController_1.SupplierController(menu);
const menuControllers = new Map();
menuControllers.set('Place Order', orderController);
menuControllers.set('Manage Suppliers', supplierController);
menuControllers.set('Manage Inventory', inventoryController);
const mainController = new MainController_1.MainController(menu, menuControllers);
mainController.rootAction();
